export const data = [
  {
    firstName: "John",
    lastName: "Doe",
    createdBy: "johndoe1",
    description: "Software Engineer",
    startDate: "2021-01-01",
    signatureCatchPhrase: "Write clean code!",
    id: "01",
    userId: "1000",
  },
  {
    firstName: "John",
    lastName: "Doe",
    createdBy: "johndoe2",
    description: "Software Engineer",
    startDate: "2021-01-01",
    signatureCatchPhrase: "Write clean code!",
    id: "02",
    userId: "10002",
  },
  {
    firstName: "John",
    lastName: "Doe",
    createdBy: "johndoe3",
    description: "Software Engineer",
    startDate: "2021-01-01",
    signatureCatchPhrase: "Write clean code!",
    id: "03",
    userId: "10003",
  },
  {
    firstName: "John",
    lastName: "Doe",
    createdBy: "johndoe4",
    description: "Software Engineer",
    startDate: "2021-01-01",
    signatureCatchPhrase: "Write clean code!",
    id: "04",
    userId: "10004",
  },
  {
    firstName: "John",
    lastName: "Doe",
    createdBy: "johndoe5",
    description: "Software Engineer",
    startDate: "2021-01-01",
    signatureCatchPhrase: "Write clean code!",
    id: "05",
    userId: "10005",
  },
  {
    firstName: "John",
    lastName: "Doe",
    createdBy: "johndoe6",
    description: "Software Engineer",
    startDate: "2021-01-01",
    signatureCatchPhrase: "Write clean code!",
    id: "06",
    userId: "10006",
  },

  // Add more mock data as needed
];
